version: '3'
services:
  mysql: # 服务名称
    image: mysql:latest # 或其它mysql版本
    container_name: mysql # 容器名称
    environment:
      - MYSQL_ROOT_PASSWORD=123456 # root用户密码
#      - TZ=Asia/Shanghai # 设置容器时区 我这里通过下面挂载方式同步的宿主机时区和时间了,这里忽略
    volumes:
      - ./mysql/log:/var/log/mysql # 映射日志目录，宿主机:容器
      - ./mysql/data:/var/lib/mysql # 映射数据目录，宿主机:容器
      - ./mysql/conf.d:/etc/mysql/conf.d # 映射配置目录，宿主机:容器
    ports:
      - 3306:3306 # 指定宿主机端口与容器端口映射关系，宿主机:容器
    restart: always # 容器随docker启动自启
