server:
  port: 8082
mysql_ip: 127.0.0.1
school: 127.0.0.1
provider: 127.0.0.1
#Spring配置
spring:
  application:
    name: provider-product
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql_ip}:3306/demo?serverTimezone=GMT%2B8&&useUnicode=true&&characterEncoding=utf-8
    username: root
    password: 123456
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 100
      connection-timeout: 14400000 
    # hikari
    hibernate: #重启目录
      ddl-auto: none
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
mybatis-plus:
   #实体扫描，多个package用逗号或者分号分隔
   type-aliases-package: net.mw.springcloud.pojo.po
   configuration:
      #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
      map-underscore-to-camel-case: true
      cache-enabled: false
      #当查询数据为空时字段返回为null，不加这个查询数据为空时，字段将被隐藏
      call-setters-on-nulls: true
      auto-mapping-behavior: full
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
   global-config:
      # 逻辑删除配置
      db-config:
         #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
        # id-type: id_worker
         #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
        # field-strategy: not_empty
         # 删除前
         logic-not-delete-value: 1
         # 删除后
         logic-delete-value: 0
# 使用Base64对该令牌进行编码
pagehelper:
   helperDialect: mysql
   reasonable: true
   supportMethodsArguments: true
   params: count=countSql
logging:
   file: mylogfile.log
   path: logs
   level:
      net:
         mw: debu
   pattern:
      file: '%d{yyyy年-MM月-dd日 HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
      console: '%d{yyyy年-MM月-dd日 HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'

eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${provider}
    instance-id: provider-product-${random.int}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${school}:8000/eureka/